# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d037626f95284f8eca86d490a9f77214e10a1bb7ab2c92948402c2057c620f74b29a7b644c5d492f6ebcef1337c15c312aa2f98d8fc006b6fb1c7b30023619cb

test:
  secret_key_base: 6373aff830553638e7ac7f0b509f564073ae959b49368c6d067b78d470ea76c0c4b1c2624e3edace6605aaac88b1012da5e83767971a650b605cdd9e5483960c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
